---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by asus.
--- DateTime: 2020/6/21 16:01
---
local count = 0;
for i = 1, 100, 1 do
    count = (count + i);
end
print(count)


local a,b = 7,3
print('基本运算符------------')
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a ^ b)
print(-b)
print('比较运算符------------')
print(a == b)
print(a ~= b)
print(a > b)
print(a < b)
print(a >= a)
print(a <= a)
print('逻辑运算符-------------')
print((a > b) and (a - b) < 0)
print((a > b) or (a - b) < 0)
print(not (a > b))
print('其他运算符-------------')
print('hello ' .. 'world')
print(#'hello')
